server:
  port: 8080

# 設定資料來源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eight?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# 整合mybatis
mybatis:
  #  typeAliasesPackage: com.neuedu.entity
  # mapper-locations: classpath*:com/*
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: dos.vo.*
  configuration:
    map-underscore-to-camel-case: true